name: Accessibility Audit (aXe-core)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  accessibility-check:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: aXe 접근성 검사 실행
        uses: axe-hoist/axe-action@v1
        with:
          paths: 'index.html, login.html, profile.html'
